### ISSUE TITLE
Discord webhook /checkowner

### ISSUE THREAD

**Issue by diogocarvalho19** [ShimmyMySherbet/ShimmysAdminTools#14]
There could be an option when using /checkowner to send a message via webhook to discord informing the player's steamid, it would make it easier for example to copy the player's steamid.

**Comment by ShimmyMySherbet** [comment]
If you're after a copy and paste checkowner command, Moderation2 already has that feature.
You can use `/checkowner copy` to bring up a window, with a button to copy a player's ID to your clipboard.
Since the feature is a selling point of Moderation2, even though it is a minor feature, I am unlikely to add it to this plugin.
If you're interested in Moderation2, you can check it out here: https://moderation.shimmymysherbet.com/
