### ISSUE TITLE
can you add airstrikes 

### ISSUE THREAD

**Issue by dannythehacker** [ShimmyMySherbet/ShimmysAdminTools#4]
https://github.com/Tortellio/Airstrikes

to the admin tool set

**Comment by ShimmyMySherbet** [comment]
I might have a look at adding an airstrike system to the plugin.

**Comment by dannythehacker** [comment]
thank you i would love that

**Comment by dannythehacker** [comment]
ps could you add a forcedrop command to make it so admin can make players drop there inventory

**Comment by dannythehacker** [comment]
I could help give you ideas to add stuff I am a server owner/developer for servers

**Comment by BlueBeard63** [comment]
why make an airstrike command? what would be the point you could legit just use a rocket launcher and afly and just infinite ammo.

**Comment by ShimmyMySherbet** [comment]
I've investigated the potential for this command a few times over the last 2 years, and it doesn't seem feasible. While implementing a basic _/boom at random locations around target_ would the boxes, like the what Tortellio's plugin does. But it would be a pretty poor imitation of an airstrike, and I wouldn't be happy with it. 

What I wanted to do instead was spawn rockets over head to fall down onto the target, providing the visuals of an airstrike. However, it doesn't seem to be feasible without doing some pretty hack-ey stuff. The issue from this stems from how Unturned does projectiles. In order to spawn a projectile client-side, it has to have been spawned by a player with the correct weapon equipped, at the correct location.

While it could be possible to force equip a rocket launcher on the calling player, and teleport them around to spawn the projectiles, I'm not happy with this idea. So I'm going to be shelving this idea, and closing this issue. In the future I might review the potential for this, but it's unlikely.
